quarkus.flyway.enabled=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres

quarkus.datasource.password=root
quarkus.datasource.username=root

quarkus.http.port=8080
quarkus.datasource.db-kind=postgresql

quarkus.datasource.reactive.url=postgresql://localhost:5432/postgres
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.packages=github.com.fabriciolfj.entities
quarkus.kubernetes.liveness-probe.initial-delay=10
quarkus.kubernetes.liveness-probe.period=2
quarkus.kubernetes.liveness-probe.timeout=5